---
title: "P8105_hw6_yj2752"
author: "Yixuan Jiao"
output: html_document
---

## Import packages

```{r}
library(tidyverse)
library(purrr)
```

## Problem2
First, cleaning the dataset. Certain cities have been excluded, only white and black are kept for race analysis. Unknown sex are dropped.
```{r}
homicide <- 
  read_csv("./data/homicide-data.csv") %>%
  mutate(city_state = str_c(city,",",state),
         victim_age = as.numeric(victim_age),
         resolved_binary = if_else(disposition == "Closed by arrest", 1, 0)) %>%
  filter(! city_state %in% c("Dallas,TX" ,"Phoenix,AZ","Kansas City,MO","Tulsa,AL")) %>%
  filter(victim_race %in% c("White","Black")) %>%
  filter(victim_sex %in% c("Male","Female")) %>%
  select(city_state,resolved_binary,victim_age,victim_race,victim_sex)
```
Fitting the linear model for Baltimore, MD with resolved status as outcome and age, sex, race as predictors.
```{r}
fit_logistic_homicide = 
  homicide %>% 
  filter(city_state == "Baltimore,MD") %>%
  glm(resolved_binary ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) 
```
The 
```{r}
fit_logistic_homicide %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate),
         CI_lower = exp(estimate - 1.96*std.error),
         CI_upper = exp(estimate + 1.96*std.error)) %>%
  select(term, log_OR = estimate, OR, CI_lower, CI_upper, p.value) %>% 
  knitr::kable(digits = 3)
```

```{r}
homicide <- 
  homicide %>%
  nest(data = -city_state) %>%
  mutate(linear_model = map(.x = data, ~glm(resolved_binary ~ victim_age + victim_race + victim_sex, data = .x, family =  binomial()) %>% broom::tidy())) %>%
  unnest(linear_model) %>%
  mutate(OR = exp(estimate),
         CI_lower = exp(estimate - 1.96*std.error),
         CI_upper = exp(estimate + 1.96*std.error)) %>%
  select(city_state,term, log_OR = estimate, OR, CI_lower, CI_upper, p.value) %>%
  filter(term == "victim_sexMale")

homicide %>% knitr::kable(digits = 3)
```

```{r}
homicide %>%
  mutate(city_state = fct_reorder(city_state,OR)) %>%
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

